spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 9901

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:conf1234}